// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxufzbrkouhznesqpawq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4dWZ6YnJrb3Voem5lc3FwYXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjM5ODYsImV4cCI6MjA2MzAzOTk4Nn0.Xqx__FOt9N1K1o7brTETWtHbQ0ljgOTSes7qrvLJkx8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);